In [ ]:
# Exercise: 4.1
# Problem - 1: Array Creation:

#1. Initialize an empty array with size 2X2.
import numpy as np
empty_array = np.empty((2, 2))
print("Empty Array (2x2): ")
print(empty_array)

Empty Array (2x2): 
[[4.9529148e-310 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]


In [ ]:
#2. Initialize an all one array with size 4X2.
import numpy as np

ones_array = np.full((4, 2), fill_value=1)

print("All-ones 4x2 array:")
print(ones_array)


All-ones 4x2 array:
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
import numpy as np

filled_array = np.full((3, 3), 7)

print("3x3 array filled with 7.5:")
print(filled_array)

3x3 array filled with 7.5:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
import numpy as np

given_array = np.array([[1, 2, 3], [4, 5, 6]])

zeros_array = np.zeros_like(given_array)

print("Given array:")
print(given_array)

print("\nZeros array with the same shape and type:")
print(zeros_array)

Given array:
[[1 2 3]
 [4 5 6]]

Zeros array with the same shape and type:
[[0 0 0]
 [0 0 0]]


In [ ]:
#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
import numpy as np

given_array = np.array([[2, 3, 4], [5, 6, 7]])

ones_array = np.ones_like(given_array)

print("Given array:")
print(given_array)

print("\nOnes array with the same shape and type:")
print(ones_array)


Given array:
[[2 3 4]
 [5 6 7]]

Ones array with the same shape and type:
[[1 1 1]
 [1 1 1]]


In [ ]:
#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
import numpy as np

new_list = [1, 2, 3, 4]
array= np.array(new_list)

print("List:")
print(new_list)

print("\nConverted NumPy array:")
print(array)

List:
[1, 2, 3, 4]

Converted NumPy array:
[1 2 3 4]


In [ ]:
# Exercise: 4.1.1
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

import numpy as np
arr_range = np.arange(10, 50)
print("Array with values from 10 to 49:")
print(arr_range)

Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}

import numpy as np
array = np.arange(9)
matrix = array.reshape(3, 3)
print("3x3 matrix with values from 0 to 8:")
print(matrix)

3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3. Create a 3X3 identity matrix.{Hint:np.eye()}

import numpy as np
identity_matrix = np.eye(3,3)
print("3x3 Identity matrix:")
print(identity_matrix)

3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4. Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}

import numpy as np
random_array = np.random.random(30)
mean = random_array.mean()
print("Random array:")
print(random_array)
print("\nMean of the array:", mean)

Random array:
[0.07889779 0.76223116 0.09998954 0.00336956 0.67404364 0.94291467
 0.40356556 0.18487265 0.09677804 0.13905336 0.38775105 0.51966755
 0.9651144  0.26023673 0.73371083 0.90928361 0.81444682 0.24677851
 0.3106625  0.04665063 0.44167277 0.73410914 0.26626255 0.79175925
 0.15604826 0.55300929 0.70541915 0.96788663 0.88074537 0.64202673]

Mean of the array: 0.4906319247890193


In [ ]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.

import numpy as np
array = np.random.random((10, 10))
min = array.min()
max = array.max()
print("\nMinimum value:", min)
print("Maximum value:", max)


Minimum value: 0.026749337636985726
Maximum value: 0.9919692482612531


In [ ]:
#6. Create a zero array of size 10 and replace 5th element with 1.

import numpy as np
zero_array = np.zeros(10)
zero_array[4] = 1
print("Array after replacing 5th element with 1:")
print(zero_array)

Array after replacing 5th element with 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7. Reverse an array arr = [1,2,0,0,4,0].

import numpy as np
array = np.array([1,2,0,0,4,0])
reversed_array= array[::-1]
print("Original array: ",array)
print("Reversed array: ",reversed_array)

Original array:  [1 2 0 0 4 0]
Reversed array:  [0 4 0 0 2 1]


In [ ]:
#8. Create a 2d array with 1 on border and 0 inside.

import numpy as np
size=5
array = np.zeros((size, size), dtype=int)
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print("2D array with 1 on the border and 0 inside:")
print(array)

2D array with 1 on the border and 0 inside:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.

import numpy as np
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1  #Fill 1 on odd rows, even columns
checkerboard[::2, 1::2] = 1  #Fill 1 on even rows, odd columns
print("8x8 Checkerboard matrix:")
print(checkerboard)

8x8 Checkerboard matrix:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Problem - 3: Array Operations:

#1. Add the two array.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print("Adding array x and y: \n", np.add(x,y))

Adding array x and y: 
 [[ 6  8]
 [10 13]]


In [ ]:
#2. Subtract the two array.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print("Subtracting array x and y: \n",np.subtract(x,y))

Subtracting array x and y: 
 [[-4 -4]
 [-4 -3]]


In [ ]:
#3. Multiply the array with any integers of your choice.

import numpy as np
v = np.array([9,10])
w = np.array([11,12])

multi_v= np.multiply(v,5)
multi_w=np.multiply(w,7)
print("v being multiplied by 5: ",multi_v)
print("w being multiplied by 7: ",multi_w)


v being multiplied by 5:  [45 50]
w being multiplied by 7:  [77 84]


In [ ]:
#4. Find the square of each element of the array.

import numpy as np
v = np.array([9,10])
w = np.array([11,12])
square_v = np.square(v)
square_w=np.square(w)
print(square_v)
print(square_w)

[ 81 100]
[121 144]


In [ ]:
#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Dot product of v and w: \n", np.dot(v,w), "\n")
print("Dot product of x and v: \n", np.dot(x,v), "\n")
print("Dot product of x and y: \n", np.dot(x,y), "\n")

Dot product of v and w: 
 219 

Dot product of x and v: 
 [29 77] 

Dot product of x and y: 
 [[19 22]
 [50 58]] 



In [ ]:
#6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))

print("Concatenate x and y along rows:\n",concat_xy_row)
print("Concatenate v and w along colums:\n",concat_vw_col)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along colums:
 [[ 9 10]
 [11 12]]


In [ ]:
#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
concat_xv = np.concatenate(x,v)
print(concat_xv)

#An error occured because the dimensions along the axis being concatenated must align.

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
# Problem - 4: Matrix Operations:

import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)
I = np.eye(2)
print("Multiplication of A and inverse of A):")
print(np.dot(A, A_inv))
print("\nIdentity matrix:")
print(I)

# 2. Prove AB ≠ BA
AB = np.dot(A,B)
print("A.B : \n", AB, "\n")
BA = np.dot(B,A)
print("B.A : \n", BA, "\n")
print("AB == BA ? : ", np.allclose(AB,BA), "\n")

# 3. Prove (AB)ᵀ = BᵀAᵀ
trans_of_AB = np.transpose(AB)
print("Transpose of AB: \n",trans_of_AB, "\n")
trans_of_B = np.transpose(B)
trans_of_A = np.transpose(A)
A_trans_b_trans = np.dot(trans_of_B, trans_of_A)
print("A transpose.B transpose : \n", A_trans_b_trans, "\n")
print("Is (AB)ᵀ equal to BᵀAᵀ ?: ", np.allclose(trans_of_AB, A_trans_b_trans), "\n")

Multiplication of A and inverse of A):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix:
[[1. 0.]
 [0. 1.]]
A.B : 
 [[23 13]
 [51 29]] 

B.A : 
 [[36 44]
 [13 16]] 

AB == BA ? :  False 

Transpose of AB: 
 [[23 51]
 [13 29]] 

A transpose.B transpose : 
 [[23 51]
 [13 29]] 

Is (AB)ᵀ equal to BᵀAᵀ ?:  True 

Solution [x, y, z]:
[ 2.  1. -2.]


In [2]:
# Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

det_A = (A[0, 0] * (A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]) -
         A[0, 1] * (A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]) +
         A[0, 2] * (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0]))

print("Determinant of A:", det_A)

# Step 2: Cofactor matrix
cofactor_matrix = np.array([
    [(A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]), -(A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]), (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0])],
    [-(A[0, 1] * A[2, 2] - A[0, 2] * A[2, 1]), (A[0, 0] * A[2, 2] - A[0, 2] * A[2, 0]), -(A[0, 0] * A[2, 1] - A[0, 1] * A[2, 0])],
    [(A[0, 1] * A[1, 2] - A[0, 2] * A[1, 1]), -(A[0, 0] * A[1, 2] - A[0, 2] * A[1, 0]), (A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0])]
])

# Step 3: Adjoint of A (transpose of cofactor matrix)
adjoint_A = cofactor_matrix.T

# Step 4: Inverse of A
inverse_A = adjoint_A / det_A
print("\nInverse of A:\n", inverse_A)

# Step 5: X = A⁻¹B
X = np.dot(inverse_A, B)
print("\nSolution (x, y, z):", X)

Determinant of A: -19

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution (x, y, z): [ 2.  1. -2.]


In [ ]:
# Solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Inverse of A using np.linalg.inv
A_inv = np.linalg.inv(A)

# X = A⁻¹B
X = np.dot(A_inv, B)

print("Inverse of A:\n", A_inv)
print("\nSolution (x, y, z):", X)

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution (x, y, z): [ 2.  1. -2.]


In [ ]:
# 4.2 Experiment: How Fast is Numpy?

# 1. Element-wise Addition:

import time

list1=[i for i in range(1,100000)]
list2=[j for j in range(1,100000)]

print("1. Element-wise Addition: \n")
start_at = time.time()
sum1 = [list1[i] + list2[i] for i in range(len(list1))]
end_at = time.time()
print("Time taken for this operation using Python Lists is: ", end_at-start_at, "seconds.\n")

arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_at = time.time()
sum2 = arr1 + arr2
end_at = time.time()
print("Time taken for this operation using NumPy Arrays is:", end_at - start_at, "seconds.")

1. Element-wise Addition: 

Time taken for this operation using Python Lists is:  0.017606735229492188 seconds.

Time taken for this operation using NumPy Arrays is: 0.003744840621948242 seconds.


In [ ]:
# 2. Element-wise Multiplication:

list1=[i for i in range(1,100000)]
list2=[j for j in range(1,100000)]

print("Element-wise Multiplication: \n")
start_at = time.time()
product1 = [list1[i] * list2[i] for i in range(len(list1))]
end_at = time.time()
print("Time taken for this operation using Python Lists is: ", end_at-start_at, "seconds.\n")

arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_at = time.time()
product2 = arr1*arr2
end_at = time.time()
print("Time taken for this operation using NumPy Arrays is:", end_at - start_at, "seconds.")

Element-wise Multiplication: 

Time taken for this operation using Python Lists is:  0.01908731460571289 seconds.

Time taken for this operation using NumPy Arrays is: 0.006129741668701172 seconds


In [ ]:
# 3. Dot Product :
list1=[i for i in range(1,100000)]
list2=[j for j in range(1,100000)]

print("Dot product: \n")
start_at = time.time()
product1 = [list1[i] * list2[i] for i in range(len(list1))]
end_at = time.time()
print("Time taken for this operation using Python Lists is: ", end_at-start_at, "seconds.\n")

arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_at = time.time()
product2 = np.dot(arr1, arr2)
end_at = time.time()
print("Time taken for this operation using NumPy Arrays is: ", end_at - start_at, "seconds.")

Dot product: 

Time taken for this operation using Python Lists is:  0.023779869079589844 seconds.

Time taken for this operation using NumPy Arrays is:  0.0021834373474121094 seconds


In [ ]:
# 4. Matrix Multiplication

print("Matrix Multiplication:\n")

matrix1 = [[i for i in range(100)] for _ in range(100)]
matrix2 = [[j for j in range(100)] for _ in range(100)]

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end_time = time.time()
print(f"Time taken for this operation using Python Lists is: {end_time - start_time:.5f} seconds.\n")

# Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"Time taken for this operation using NumPy is: {end_time - start_time:.5f} seconds.")

Matrix Multiplication:

Time taken for this operation using Python Lists is: 0.21522 seconds.

Time taken for this operation using NumPy is: 0.00174 seconds.
